### ISSUE TITLE
Missing Requirements

### ISSUE THREAD

**Issue by tsafs** [White-Link/UnsupervisedScalableRepresentationLearningTimeSeries#9]
Hi

I wanted to test your code within a docker container and noticed that the requirements for Java and GCC were not listed. Installing these two on my docker container made the code work and I haven't found any errors yet. 

I have attached my `Dockerfile` and `docker-compose.yml` for anyone who might want to use it. The sample code in the README executes fine. I haven't tested anything else yet.

Dockerfile
```
FROM pytorch/pytorch

# Install OpenJDK-8
RUN apt-get update && \
    apt-get install -y openjdk-8-jdk && \
    apt-get install -y ant && \
    apt-get clean;

# Fix certificate issues
RUN apt-get update && \
    apt-get install ca-certificates-java && \
    apt-get clean && \
    update-ca-certificates -f;

# Setup JAVA_HOME -- useful for docker commandline
ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME

# Install gcc
RUN apt-get update && \
	apt-get install -y gcc

# install python dependencies
RUN pip install --upgrade pip
RUN pip install \
	numpy \
	matplotlib \
	PyQt5 \
	PyQtWebEngine \
	orange3 \
	pandas \
	python-weka-wrapper3 \
	scikit-learn==0.20.0 \
	scipy
```

docker-compose.yml
```
version: '2.3'
services:
  dev:
    container_name: jeanyves
    build:
      context: . # path to folder containing Dockerfile
      dockerfile: Dockerfile
    image: jeanyves:1.0.0
    volumes:
    - path/to/repo:/work # path to this git repo
    - path/to/data:/data # path to data, e.g. UCR
    - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
    - DISPLAY=$DISPLAY
    runtime: nvidia
    environment:
    - NVIDIA_VISIBLE_DEVICES=all
    working_dir: /work
    user: 1001:1001 # can probably be discarded
    tty: true
    stdin_open: true
```

To run the container make sure to install docker as well as docker-compose. Then:
```
cd path/to/docker-compose-yml-folder
docker-compose up dev
```

In another terminal:
```
docker exec -it jeanyves bash
python ucr.py --dataset Mallat --path /data/UCRArchive_2018 --save_path /work/results/models --hyper default_hyperparameters.json --cuda --gpu 0
```

Make sure to manually create the output folder specified under `--save_path`, if it does not already exist. Otherwise the script will fail with a `no such file or directory` exception.
